"""Added election_id column to ElectionData model

Revision ID: 6d361c20db0e
Revises: b9730c09f47c
Create Date: 2024-08-17 20:52:27.202748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d361c20db0e'
down_revision = 'b9730c09f47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'elections_data', ['election_id'], ['id'])

    with op.batch_alter_table('elections_data', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections_data', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('election_id')

    # ### end Alembic commands ###
